### ISSUE TITLE
strange behaviour of resample()

### ISSUE THREAD

**Issue by tischi** [mcib3d/mcib3d-core#10]
When executing the resample function on an `ImageInt`, the wrapped ImagePlus changes its dimensions.  

The dimensions of `binnedNucleusLabelMask` are changed from

98x106x1x**26**x1

to

98x106x1x**1**x1

(see last lines of corresponding screenshots).

Indicating that the `.resample(  )` command modifies the input image...

## Before:
![image](https://user-images.githubusercontent.com/2157566/37163118-3b1f860c-22f7-11e8-8656-8c893428e687.png)

## After:
![image](https://user-images.githubusercontent.com/2157566/37163130-493b829a-22f7-11e8-9827-6960354834b3.png)

**Comment by mcib3d** [comment]
Hi tischi,

The resample function is actually calling the StackProcessor resize function of ImageJ. Yes this function may change the input image as well. I will check and will duplicate the image before resizing.

**Comment by tischi** [comment]
This would be great!

**Comment by mcib3d** [comment]
Issue solved in 596399d392c376af583a511eb6d4f0109ceb965f
