### ISSUE TITLE
O(n^2) time with 3D Maxima Finder

### ISSUE THREAD

**Issue by Enakcihc** [mcib3d/mcib3d-core#14]
Hi, I have been trying to use the 3D Maxima Finder to detect puncta in my 3D stack, but I realized as I use it to a larger region, the calculation time exponentially increased. I presumed it was because the exclusion criteria (points not closer than certain x, y, z radii) was performed by calculating distance between all possible combination of detected peaks. 

Is there a way to disable this check or implement a more efficient algorithm?

**Comment by Enakcihc** [comment]
The simplest implementation I can see is to use the maximum filter with the same distance parameters and compare with the value of the peak pixels.

**Comment by mcib3d** [comment]
Hi,
The implementation is based on the Maximum Finder in ImageJ. After peaks detection, peaks are sorted by intensity, a flooding is performed (using noise parameter) to remove other peaks within noise range. I tried to speed up the flooding algorithm but yes it can take very long time to compute on big images.
