### ISSUE TITLE
Weka version clash with Fiji

### ISSUE THREAD

**Issue by tischi** [mcib3d/mcib3d-core#15]
Hi Thomas,  @mcib3d @ctrueden 

Would it be possible for you to change the version of weka in your pom?

In your pom it is: `weka 3.7.6`
https://github.com/mcib3d/mcib3d-core/blob/master/pom.xml#L128

In Fiji parent pom it is: `weka-dev 3.9.3`
- https://github.com/scijava/pom-scijava/blob/master/pom.xml#L875

For me this is creating issues, because whenever I use your 3D Image Suite it downloads the `weka 3.7.6` version from your update sites which clashes with the newer `weka-dev 3.9.3` version that is shipped with Fiji. The reason that your version is not simply overwritten by the later one in Fiji is, I think, the different artifact id `weka-dev` vs `weka`. Thus, could you please check whether you could live with the `weka-dev` version for 3D Image Suite?

**Comment by mcib3d** [comment]
Hi @tischi ,

I updated the pom to use the weka-dev version, cf8cf5ed538e2333f8b4a3893b7a25c8d757f9f1.

Best, 

Thomas
