### ISSUE TITLE
Very basic question about plugin usage

### ISSUE THREAD

**Issue by leboero** [mcib3d/mcib3d-core#17]
Hi! I have just found this plugin today. I'm still new in the image analysis field but I have the following problem

I have confocal stacks with two channels, and I would like to threshold the images as well as possible. Then I would like to do the following (ideally for user-defined ROIs) 

1) Make measurements of the volume of the signal (mainly there are like dots) for each channel

2) Quantify the number of colocalizing puncta for each ROI.

I have another way of doing 2), but I didn't find a good way of performing 1). I have tried with the 3d Object Counter but I'm not quite satisfied with the results given that the thresholding algorithm could be not optimal.

I have read the wiki of the plugin. I chose my ZStack as the spots and used the local maxima function to get the seeds. Then I tried to select the ROIs and when I tested I didn't get a result. I know that must be a very silly question but I'm not sure if I have the make a roi for each seed or if the rois can be the ones that I would like to use in my further analysis.

Sorry again

Luis

**Comment by mcib3d** [comment]
Hi @leboero ,

I suggest you to post your question on the [forum](https://forum.image.sc/) . This thread is mostly to talk about the code. 
Regarding your question I may suggest you to have a look at the plugins using this library in the [3D ImageJ Suite](http://imagejdocu.tudor.lu/doku.php?id=plugin:stacks:3d_ij_suite:start), especially the  segmentation [plugins](http://imagejdocu.tudor.lu/plugin/segmentation/3d_spots_segmentation/start).
