### ISSUE TITLE
Issue: Dilate function for Object3D does not work properly.

### ISSUE THREAD

**Issue by nhuhoa** [mcib3d/mcib3d-core#2]
Dilate function for Object3D does not work properly.
Need to verify it. 
Object3D obj;   //an object3D
obj.getDilatedObject(radX, radY, radZ)  //get dilated region of this object

**Comment by mcib3d** [comment]
This is fixed by commit e7b7c00a0f65d92fe6abe8375a00b3ed25e2a326
