### ISSUE TITLE
3D Hysteresis doesn't work with 32bit

### ISSUE THREAD

**Issue by j01993** [mcib3d/mcib3d-core#21]
Hi 3D Image suite developers,

I've been using your software for a year now and it has been very helpful.
I realized that Hysteresis thresholding doesn't work properly with 32bit in the latest release.
This function used to be part of my image processing pipeline and now I am returning to the previous release to use this function.
I wanted to let you know.

**Comment by mcib3d** [comment]
Hi @j01993 ,

Thanks for the feedback, there was a major release recently and may be some functions are not working properly yet.

However, I cannot reproduce the problem, your input image is 32-bit ? Are you using the _labelling_ mode ? 

Please note the official repository is now https://framagit.org/mcib3d/mcib3d-core .
