### ISSUE TITLE
Issue: FastFilters3D function do not work well with big radius of XYZ

### ISSUE THREAD

**Issue by nhuhoa** [mcib3d/mcib3d-core#3]
At Object3D class, function getMorphoObject():

int filter = FastFilters3D.MAX;
segImage2 = FastFilters3D.filterIntImage(getLabelImage(), filter, radX, radY, radZ, 0, true);
Test 1: input small parameter for radX, radY, radZ, work well
Test 2: input big number for radX, radY, radZ, program do not work properly.

**Comment by mcib3d** [comment]
This is also closed by commit e7b7c00a0f65d92fe6abe8375a00b3ed25e2a326
