### ISSUE TITLE
Current version of 3D Suite does not work with up-to-date Fiji due to wrong Java3D/Vecmath

### ISSUE THREAD

**Issue by imagejan** [mcib3d/mcib3d-core#4]
The current [downloads of Fiji ](http://imagej.net/Fiji/Downloads) come bundled with Java 8 and include a forked Java3d (`org.scijava.j3dcore`, `org.scijava.j3dutils` and `org.scijava.vecmath`). The 3d Suite plugins fail with errors such as:

```
java.lang.ClassCastException: org.scijava.vecmath.Point3f cannot be cast to javax.vecmath.Point3f
```

I suggest updating all occurrences of `javax.vecmath.*` with their corresponding `org.scijava.vecmath.*` versions.

**Comment by mcib3d** [comment]
Hi,

I updated using the Fiji fork, need some test before official release. Thanks for the pull.

Thomas

**Comment by imagejan** [comment]
Thanks for updating! I'm willing to test, but the current mcib-plugins doesn't compile for me because maven cannot resolve the mcib-core dependency.
May I suggest updating both projects to use [SemVer](http://imagej.net/Versioning), so the maven artifacts can be deployed to `maven.imagej.net` and easily be consumed by 3rd party projects?

**Comment by mcib3d** [comment]
Thanks for the comments, I must admit I am discovering maven and still struggling a bit ;) . About the versioning yes this one is Major, since I now use vecmath from fiji. Maybe I should give you write access to MCIB if you are willing to use this library and hopefully improve it.

**Comment by imagejan** [comment]
I'd suggest to use your version number (3.8) in the `pom.xml` as well:

```
    <groupId>mcib</groupId>
    <artifactId>mcib-core</artifactId>
    <version>3.8.0</version>
```

and then use versions like `<version>3.8.1-SNAPSHOT</version>` on the master branch while developing, and release a `<version>3.8.1</version>` etc. once in a while when you also want to upload to the update site. (To avoid version mismatch, it's then easiest to delete any additional occurences of the version numbers, e.g. in [AboutMCIB.java](https://github.com/mcib3d/mcib3d-core/blob/47a3b5f1af16e94973ba615bb0197a369e2d6d87/src/main/java/mcib3d/utils/AboutMCIB.java#L30))

I can submit a pull request during next week if you like. I'd then ask @ctrueden to step in regarding the procedure of deploying the builds to the maven repository.

**Comment by mcib3d** [comment]
Ok, thanks, sounds good. For maven we are using jitpack.io and is working fine.

**Comment by imagejan** [comment]
> For maven we are using jitpack.io and is working fine.

Oh, alright, sorry I didn't know this. Then I guess it's all fine and nothing needs to be changed.

> need some test before official release.

After renaming the `mcib3d-plugins-master-SNAPSHOT.jar` to contain an underscore and copying both artefacts to my Fiji installation, all worked well with using the 3D Manager and doing some measurements. :+1: from my side for uploading

**Comment by mcib3d** [comment]
ok, good, thanks again. Will release next week.

**Comment by ctrueden** [comment]
@mcib3d Just wanted to say thank you for working on this. I'm glad you managed to get everything squared away. And as always, let me know if there is anything I can do to help in the future.
