### ISSUE TITLE
radiusMax - Watershed 3D Voronoi 

### ISSUE THREAD

**Issue by nhuhoa** [mcib3d/mcib3d-core#7]
At mcib3d-core plugin: 
    mcib3d.image3d.regionGrowing.Watershed3DVoronoi
Function computeVoronoi returns null if radiusMax = NaN
Need a small function to validate input radius max parameter: 
For ex: 
public Watershed3DVoronoi(ImageInt seeds, float radiusMax) {
       if(Float.isNaN(radiusMax))
       {
                this.seeds = seeds;
       }
      else{
               this.seeds = seeds;
               this.radiusMax = radiusMax;
      }
        
    }

public void setRadiusMax(float radiusMax) {
       if(!Float.isNaN(radiusMax))
       {
                this.radiusMax = radiusMax;
                 voronoi = null;
       }
    }

**Comment by mcib3d** [comment]
Hi Hoa,

Thanks for noticing this potential problem. It is corrected in 9c4d4b0e327e9b0bed3cc0e60458a9e0ec86c786. 

Thomas
