### ISSUE TITLE
Remove the log output  at MereoAnalysis class

### ISSUE THREAD

**Issue by nhuhoa** [mcib3d/mcib3d-core#8]
package mcib3d.geom  --> MereoAnalysis.java

Could you give more options to display the output at log file. 
Thanks a lot, 

For example: 

Current version: 
public void computeFastRelationships() 
{
// code
      for (int a = 0; a < nbA; a++) 
      {
           IJ.log("Processing object A" + a);   //in case of a big amount of data, this line print to screen     numerous times 
      }
}

Updated version could be: 
public void computeFastRelationships(boolean show) 
{
// code
      for (int a = 0; a < nbA; a++) 
      {
          if(show)
          {
           IJ.log("Processing object A" + a);  
           }
      }
}

**Comment by mcib3d** [comment]
Hi,

Ok, check 98f686a17bc3577d571eae4a7301df8e4d262609. Please use the method setLog with NoLog : 

.setLog(new NoLog());

Thomas
