### ISSUE TITLE
Watershed Split Region Algorithm

### ISSUE THREAD

**Issue by nhuhoa** [mcib3d/mcib3d-core#9]
Testing mcib3d.image3d.regionGrowing.Watershed3D
The watershed label for boundary is depend on gaussian blur radius: 
Input: segmented image 
Objective: Split this object by two parts 

Testing: 
Test 1: smooth radius for  gaussian blur = 1
Output: 3 regions, labels = {3, 4, 5}
watershed label = 1 
Remark: well separated as expected but there exists one region(label 4) 
which contains only one pixel. Need to remove this region. How can we 
improve algo to obtain only 2 regions? 

Test2:  smooth radius for gaussian blur = 2
Output: 2 regions, labels = {3, 4}
watershed label = 1 
Remark: not well separated, over-segmented, but satify that there are 
two region as expected. 

![testing_wat](https://cloud.githubusercontent.com/assets/8064672/25987442/a092bcb0-3726-11e7-9ff5-56fd0f9d3b83.jpg)

Best, 
Hoa

**Comment by mcib3d** [comment]
Shoudl be fixed in : 
https://github.com/mcib3d/mcib3d-core/commit/06bc847064421376f587927e988e2a37e8d2615e
